language: bash
before_script:
- wget https://github.com/gohugoio/hugo/releases/download/v0.29/hugo_0.29_Linux-64bit.tar.gz
- tar -zxvf hugo_0.29_linux_amd64.tar.gz
script:
- "./hugo_0.29_Linux-64bit/hugo_0.29_Linux-64bit"
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAJ3PAN2I6XGPTRZUA
  secret_access_key:
    secure: LcoYu9Qy1vKsY58GxTG02vKskpdHkqh52YOEvpGEIY6kvaUgqwhGIPSVgxdbdse3YrkgFj/I5EDow3nFx235v+O43J4BSM65Lb55dvckBBsoJ1qQR8xw+b7AOMcTd9e0CnfceBwll1g7YYdpqOHlV1WcSysRCQyaXfvRS7ILeHt672MbNFFULVc4qyQ4+7c7NEx027cJ9w1OEbY6cVXbFVIWbW5P4gXgL1/aDyC6ZrrJPVWyhrjbc0uTdbNAUFPTzHw6My2mfJS4RwzSrrsDaoyYD64hLJZFVQowLoIVtDsMyTW3L1PTL4r/nAOywfwqt6c0zzwqxQVPu5Qqbc/ueWNb5sQ0xCEJosx69pNCPmJHNeiJNXrFjIFxH04x5od8jA2aDutb2xG5hAt1ceBF2JjL6ZYKDna6NWGvvlsxgl3g23v2HGQ9KTaEn9jmStUMiCcAVMWBBtjHl8WYe5i6kXYw06JDlV/QtVpIR1u+SDkIYBDe/wkgMB1Y0L+LDzZSTf+/03C+kAahHvssGEH9rN7WzeBr31DxPx0tqPbEEOYZRxg3XilsBnlhPtPlX2f47XEMlFMFCplpiU1hKqSVwHTW0e4psIOW7mFRWScYNdFF2wwSE1ONsSv6wgTGhM6L6keq+8dL3f92Mwt2OJc0joXwiTogBw5BIKWyETbJaD4=
  bucket: derwolfe.net
  local-dir: "./public"
  acl: public_read
  on:
    branch: master
    repo: derwolfe/derwolfe-nuevo
