baseurl = "https://derwolfe.net"
title = "Chris Wolfe"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "All rights resevered - 2016 - Chris Wolfe"
googleAnalytics = "UA-41763159-1"
paginate = 10

[Author]
    name = "Chris Wolfe"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Helllooo."
    description = "I'm Chris Wolfe, I have a poodle, and write programs."
    github = "https://github.com/derwolfe"
    twitter = "https://twitter.com/chriswwolfe"
    title = "Chris Wolfe"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Posts"
    url = "/"
    weight = 1
