baseurl = "https://derwolfe.net"
title = "Chris Wolfe"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Chris Wolfe"
googleAnalytics = "UA-41763159-1"

[Author]
    name = "Chris Wolfe"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Helllooo."
    description = "I'm Chris Wolfe"
    github = "https://github.com/derwolfe"
    twitter = "https://twitter.com/chriswwolfe"
    title = "Chris Wolfe"
    
    #footer = "Copyright Chris Wolfe; All rights reserved"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "The Posts"
    url = "/"
    weight = 1

# [[menu.main]]
#     name = "Projects"
#     url = "/project/"
#     weight = 2

# [[menu.main]]
#     name = "Contact"
#     url = "/page/contact/"
#     weight = 3

# [[menu.main]]
#     name = "About"
#     url = "/page/about/"
#     weight = 4
